name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 --ignore=E501,W503,F821 --exclude=.git,__pycache__,build,dist
      - name: Install Pylint
        run: pip install pylint
      - name: Run Pylint
        run: pylint $(git ls-files '*.py')
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check .
