name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      release_version: ${{ github.ref_name }}
      ref_type: ${{ github.ref_type }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update
          sudo apt install -y fakeroot dpkg tar gzip xz-utils

          # Prepare control file
          if [ "${ref_type}" != "tag" ]; then
            release_version="$(awk -F'"' '/^PV *=/ {print $2}' src/__init__.py)-pre"
            echo "release_version=${release_version}" >> $GITHUB_ENV
          fi
          sed -i "s/^Version: .*/Version: ${release_version}/" CONTROL/control
          sed -i "s/^\(PV *= *\).*/\1\"${release_version}\"/" src/__init__.py

          # multiboot-selector.sh must be executable
          chmod +x src/usr/bin/multiboot-selector.sh

      # Build .deb package
      - name: Build .deb package
        run: |
          mkdir -p deb_pkg/DEBIAN
          mkdir -p deb_pkg/usr/bin
          mkdir -p deb_pkg/usr/lib/enigma2/python/Plugins/Extensions/MultiBootSelector

          # Add files to publish
          cp CONTROL/control deb_pkg/DEBIAN/
          cp src/usr/bin/multiboot-selector.sh deb_pkg/usr/bin/
          cp src/*.py src/*.png deb_pkg/usr/lib/enigma2/python/Plugins/Extensions/MultiBootSelector/

          # Create deb package
          fakeroot dpkg-deb -Z xz --build deb_pkg enigma2-plugin-extensions-multibootselector_${release_version}-r0_all.deb

      # Build .ipk package
      - name: Build .ipk package
        run: |
          mkdir -p ipk_pkg/control
          mkdir -p ipk_pkg/usr/bin
          mkdir -p ipk_pkg/usr/lib/enigma2/python/Plugins/Extensions/MultiBootSelector

          # Add files to publish
          cp CONTROL/control ipk_pkg/control/
          cp src/usr/bin/multiboot-selector.sh ipk_pkg/usr/bin/
          cp src/*.py src/*.png ipk_pkg/usr/lib/enigma2/python/Plugins/Extensions/MultiBootSelector/

          # Create ipk package
          cd ipk_pkg
          tar -czvf control.tar.gz -C ./control .
          tar -czvf data.tar.gz ./usr
          echo "2.0" > debian-binary

          ar r ../enigma2-plugin-extensions-multibootselector_${release_version}-r0_all.ipk ./debian-binary ./control.tar.gz ./data.tar.gz
          cd ..

      # =============================
      # ✅ Create GitHub Release with auto-generated release notes
      # =============================
      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            enigma2-plugin-extensions-multibootselector_*_all.deb
            enigma2-plugin-extensions-multibootselector_*_all.ipk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # =============================
      # ✅ Create GitHub artifacts for testing
      # =============================
      - name: Upload build artifacts
        if: github.ref_type != 'tag' || !github.ref_type
        uses: actions/upload-artifact@v4
        with:
          name: packages_${{ env.release_version }}
          retention-days: 1
          compression-level: 9
          path: |
            enigma2-plugin-extensions-multibootselector_*_all.deb
            enigma2-plugin-extensions-multibootselector_*_all.ipk


